spring:
  application:
    name: spring_eureka_server #Eureka에 등록되는 Application 이름

eureka:
  server:
    response-cache-update-interval-ms: 500 #유레카 서버의 캐시 업데이트 주기 조정
    eviction-interval-timer-in-ms: 500 #유레카 클라이언트의 레지스트리를 받아오는 주기 조정
  client:
    register-with-eureka: true # 유레카 서버에 등록할 것인가에 대한 설정
    fetch-registry: true #유레카 서버로 부터 정보를 가져올 것인지 설정
    service-url:
      defaultZone: http://eureka-cluter-${peer.port} # 유레카 클라이언트가 서비스를 등록할 유레카 주소를 지정

  instance:
    hostname: eureka-cluter-${server.port} # 호스트 이름을 통해 접근할때 이름을 지정
